/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ConciergeRouteImport } from './routes/concierge'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as NotFoundRouteImport } from './routes/not-found'
import { Route as SupportRouteImport } from './routes/support'
import { Route as UniversitiesRouteImport } from './routes/universities'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as ArticlesIndexRouteImport } from './routes/articles.index'
import { Route as ArticlesSlugRouteImport } from './routes/articles.$slug'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as ScholarshipsIndexRouteImport } from './routes/scholarships.index'
import { Route as ScholarshipsIdRouteImport } from './routes/scholarships.$id'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminApplicationsRouteImport } from './routes/_authenticated/admin.applications'
import { Route as AuthenticatedAdminScholarshipsRouteImport } from './routes/_authenticated/admin.scholarships'
import { Route as GuidesCategorySlugRouteImport } from './routes/guides.$category.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ConciergeRoute = ConciergeRouteImport.update({
  id: '/concierge',
  path: '/concierge',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const NotFoundRoute = NotFoundRouteImport.update({
  id: '/not-found',
  path: '/not-found',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const UniversitiesRoute = UniversitiesRouteImport.update({
  id: '/universities',
  path: '/universities',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ArticlesIndexRoute = ArticlesIndexRouteImport.update({
  id: '/articles/',
  path: '/articles/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesSlugRoute = ArticlesSlugRouteImport.update({
  id: '/articles/$slug',
  path: '/articles/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const ScholarshipsIndexRoute = ScholarshipsIndexRouteImport.update({
  id: '/scholarships/',
  path: '/scholarships/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScholarshipsIdRoute = ScholarshipsIdRouteImport.update({
  id: '/scholarships/$id',
  path: '/scholarships/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminApplicationsRoute =
  AuthenticatedAdminApplicationsRouteImport.update({
    id: '/admin/applications',
    path: '/admin/applications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminScholarshipsRoute =
  AuthenticatedAdminScholarshipsRouteImport.update({
    id: '/admin/scholarships',
    path: '/admin/scholarships',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const GuidesCategorySlugRoute = GuidesCategorySlugRouteImport.update({
  id: '/guides/$category/$slug',
  path: '/guides/$category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/concierge': typeof ConciergeRoute
  '/how-it-works': typeof HowItWorksRoute
  '/not-found': typeof NotFoundRoute
  '/support': typeof SupportRoute
  '/universities': typeof UniversitiesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/scholarships/$id': typeof ScholarshipsIdRoute
  '/articles/': typeof ArticlesIndexRoute
  '/scholarships/': typeof ScholarshipsIndexRoute
  '/admin/applications': typeof AuthenticatedAdminApplicationsRoute
  '/admin/scholarships': typeof AuthenticatedAdminScholarshipsRoute
  '/guides/$category/$slug': typeof GuidesCategorySlugRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/concierge': typeof ConciergeRoute
  '/how-it-works': typeof HowItWorksRoute
  '/not-found': typeof NotFoundRoute
  '/support': typeof SupportRoute
  '/universities': typeof UniversitiesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/scholarships/$id': typeof ScholarshipsIdRoute
  '/articles': typeof ArticlesIndexRoute
  '/scholarships': typeof ScholarshipsIndexRoute
  '/admin/applications': typeof AuthenticatedAdminApplicationsRoute
  '/admin/scholarships': typeof AuthenticatedAdminScholarshipsRoute
  '/guides/$category/$slug': typeof GuidesCategorySlugRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/concierge': typeof ConciergeRoute
  '/how-it-works': typeof HowItWorksRoute
  '/not-found': typeof NotFoundRoute
  '/support': typeof SupportRoute
  '/universities': typeof UniversitiesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/scholarships/$id': typeof ScholarshipsIdRoute
  '/articles/': typeof ArticlesIndexRoute
  '/scholarships/': typeof ScholarshipsIndexRoute
  '/_authenticated/admin/applications': typeof AuthenticatedAdminApplicationsRoute
  '/_authenticated/admin/scholarships': typeof AuthenticatedAdminScholarshipsRoute
  '/guides/$category/$slug': typeof GuidesCategorySlugRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/concierge'
    | '/how-it-works'
    | '/not-found'
    | '/support'
    | '/universities'
    | '/dashboard'
    | '/articles/$slug'
    | '/auth/callback'
    | '/scholarships/$id'
    | '/articles/'
    | '/scholarships/'
    | '/admin/applications'
    | '/admin/scholarships'
    | '/guides/$category/$slug'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/concierge'
    | '/how-it-works'
    | '/not-found'
    | '/support'
    | '/universities'
    | '/dashboard'
    | '/articles/$slug'
    | '/auth/callback'
    | '/scholarships/$id'
    | '/articles'
    | '/scholarships'
    | '/admin/applications'
    | '/admin/scholarships'
    | '/guides/$category/$slug'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/concierge'
    | '/how-it-works'
    | '/not-found'
    | '/support'
    | '/universities'
    | '/_authenticated/dashboard'
    | '/articles/$slug'
    | '/auth/callback'
    | '/scholarships/$id'
    | '/articles/'
    | '/scholarships/'
    | '/_authenticated/admin/applications'
    | '/_authenticated/admin/scholarships'
    | '/guides/$category/$slug'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ConciergeRoute: typeof ConciergeRoute
  HowItWorksRoute: typeof HowItWorksRoute
  NotFoundRoute: typeof NotFoundRoute
  SupportRoute: typeof SupportRoute
  UniversitiesRoute: typeof UniversitiesRoute
  ArticlesSlugRoute: typeof ArticlesSlugRoute
  ScholarshipsIdRoute: typeof ScholarshipsIdRoute
  ArticlesIndexRoute: typeof ArticlesIndexRoute
  ScholarshipsIndexRoute: typeof ScholarshipsIndexRoute
  GuidesCategorySlugRoute: typeof GuidesCategorySlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concierge': {
      id: '/concierge'
      path: '/concierge'
      fullPath: '/concierge'
      preLoaderRoute: typeof ConciergeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/not-found': {
      id: '/not-found'
      path: '/not-found'
      fullPath: '/not-found'
      preLoaderRoute: typeof NotFoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/universities': {
      id: '/universities'
      path: '/universities'
      fullPath: '/universities'
      preLoaderRoute: typeof UniversitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/articles/': {
      id: '/articles/'
      path: '/articles'
      fullPath: '/articles/'
      preLoaderRoute: typeof ArticlesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/$slug': {
      id: '/articles/$slug'
      path: '/articles/$slug'
      fullPath: '/articles/$slug'
      preLoaderRoute: typeof ArticlesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/scholarships/': {
      id: '/scholarships/'
      path: '/scholarships'
      fullPath: '/scholarships/'
      preLoaderRoute: typeof ScholarshipsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scholarships/$id': {
      id: '/scholarships/$id'
      path: '/scholarships/$id'
      fullPath: '/scholarships/$id'
      preLoaderRoute: typeof ScholarshipsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/applications': {
      id: '/_authenticated/admin/applications'
      path: '/admin/applications'
      fullPath: '/admin/applications'
      preLoaderRoute: typeof AuthenticatedAdminApplicationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/scholarships': {
      id: '/_authenticated/admin/scholarships'
      path: '/admin/scholarships'
      fullPath: '/admin/scholarships'
      preLoaderRoute: typeof AuthenticatedAdminScholarshipsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/guides/$category/$slug': {
      id: '/guides/$category/$slug'
      path: '/guides/$category/$slug'
      fullPath: '/guides/$category/$slug'
      preLoaderRoute: typeof GuidesCategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedAdminApplicationsRoute: typeof AuthenticatedAdminApplicationsRoute
  AuthenticatedAdminScholarshipsRoute: typeof AuthenticatedAdminScholarshipsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedAdminApplicationsRoute: AuthenticatedAdminApplicationsRoute,
  AuthenticatedAdminScholarshipsRoute: AuthenticatedAdminScholarshipsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ConciergeRoute: ConciergeRoute,
  HowItWorksRoute: HowItWorksRoute,
  NotFoundRoute: NotFoundRoute,
  SupportRoute: SupportRoute,
  UniversitiesRoute: UniversitiesRoute,
  ArticlesSlugRoute: ArticlesSlugRoute,
  ScholarshipsIdRoute: ScholarshipsIdRoute,
  ArticlesIndexRoute: ArticlesIndexRoute,
  ScholarshipsIndexRoute: ScholarshipsIndexRoute,
  GuidesCategorySlugRoute: GuidesCategorySlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
